Comms 24
asc-csa/Scisat-App pull request #101
Opened 2021-04-13 16:44 UTC by coleweusthem

This will only work if you install the modified version of dash-core-components

2021-04-20 15:12 UTC, nfee006 requested changes
Seems to address comms 24. The text itself will need to be changed though. This is how it appears on my VM. 

![image](https://user-images.githubusercontent.com/11013061/115420402-19e70100-a1c9-11eb-8260-c4208795ad5e.png)
1. The word "test" should be removed.
2. It does not seem to translate. This may relate to https://github.com/asc-csa/Scisat-App/issues/105.

2021-04-20 18:45 UTC, coleweusthem commented
@nfee006, this should be fixed in #104

2021-04-22 12:32 UTC, nfee006 commented
Approved based on #104 with one minor change - capitalization should be consistent

![image](https://user-images.githubusercontent.com/11013061/115714609-4c1d6d80-a345-11eb-9254-f34447c16b81.png)

2021-04-22 12:33 UTC, nfee006 approved these changes

2021-04-22 14:29 UTC, merged