styled the pagination to match gcweb
asc-csa/Scisat-App pull request #102
Opened 2021-04-13 19:27 UTC by coleweusthem

matched the gcweb style

2021-04-20 15:25 UTC, nfee006 requested changes
Styling looks good. Some issues:
![image](https://user-images.githubusercontent.com/11013061/115421524-07b99280-a1ca-11eb-9e29-58af02021fef.png)
1. I believe that the aria-label should be in the `<a>` as opposed to the `<li>.` See https://github.com/asc-csa/ckanext-asc-csa/issues/105
2. The text does not appear to translate. Likely related to https://github.com/asc-csa/Scisat-App/issues/105
3. The English wording includes the term "goto". I understand that that's a term used in some programming languages but a space would probably be required in this context? 
4. (EDIT) Also, we'll need to get rid of the existing pagination (which I assume you already knew).
![image](https://user-images.githubusercontent.com/11013061/115424127-65e77500-a1cc-11eb-8100-431f03348d9e.png)


Here's an example of the translated pagination, stolen from ckanext-asc-csa.
`<nav role="navigation" aria-label="Navigation de pagination"><ul class="pagination"><li><a aria-label="Voir la page « Précédente" href="/fr/dataset?page=1">« Précédente</a></li> <li><a aria-label="Voir la page 1" href="/fr/dataset?page=1">1</a></li> <li class="active"><a aria-label="(page actuelle) Voir la page 2" href="/fr/dataset?page=2">2</a></li> <li><a aria-label="Voir la page 3" href="/fr/dataset?page=3">3</a></li> <li><a aria-label="Voir la page 4" href="/fr/dataset?page=4">4</a></li> <li class="disabled"><a href="#">...</a></li> <li><a aria-label="Voir la page 8" href="/fr/dataset?page=8">8</a></li> <li><a aria-label="Voir la page Suivante »" href="/fr/dataset?page=3">Suivante »</a></li></ul></nav> `

2021-04-20 18:44 UTC, coleweusthem commented
this should be sorted in #104

2021-04-22 12:35 UTC, nfee006 commented
Approved based on #104 with one minor comment/change: the English aria-labels still use the term "goto" - is that a pagination standard that I'm not aware of?

2021-04-22 12:35 UTC, nfee006 approved these changes

2021-04-22 14:55 UTC, merged